defaults:
  - data: amazon_products
  - model: sage_correlation
  - hpo: optuna_search
  - _self_

seed: 42
expt_name: "scale-sage-prod"
artifacts_dir: "./artifacts"


tracking:
  experiment_name: "Amazon-Products-GraphSAGE-Prod"
  connection_string: "sqlite:///mlflow_graphsage.db"

early_stopping:
  patience: 5
  monitor: "val_macro_f1"
  mode: "max"
